name: Update Repositories file

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update-repositories:
    runs-on: ubuntu-latest
    env:
      OUTPUT_PATH: static/repositories.json

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Update repositories file
        run: bun scripts/fetchRepositories.ts

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $OUTPUT_PATH
          git commit -m "Update $OUTPUT_PATH" || echo "No changes to commit"
          git push
